/* eslint-disable @typescript-eslint/no-explicit-any */
import { PayloadAction, createSlice } from '@reduxjs/toolkit';
import { iMovimento } from '../../@types/PreVenda';
import { iDataResultTable } from '../../@types/Table';
import { GetVendas } from './venda.thunk';

interface iVendaState {
  Current: iMovimento;
  List: iDataResultTable<iMovimento>;
  isLoading: boolean;
  errorMessage: string;
}

const initialState: iVendaState = {
  Current: {
    MOVIMENTO: 0,
    DATA: '',
    OFICINA: undefined,
    DOC: '',
    SUBTOTAL: 0,
    ACRESCIMO: 0,
    DESCONTO: 0,
    TOTAL: 0,
    AVISTA: 0,
    TIPOAVISTA: undefined,
    APRAZO: 0,
    TIPOAPRAZO: '',
    PRAZOS: undefined,
    TIPOMOV: 'PRE-VENDA',
    MOV: 'S',
    ORIGEM: '',
    CANCELADO: 'S',
    CAIXA: 0,
    IMPRESSO: 'S',
    CUPOM_FISCAL: undefined,
    MOTOBOY: 0,
    OBS1: '',
    OBS2: '',
    COM_FRETE: undefined,
    FRETE: undefined,
    FRETE_RATEIO: undefined,
    COM_NOTA: undefined,
    OS: undefined,
    DATA_REF: '',
    MOTIVO_CANCELAMENTO: undefined,
    QUEM_CANCELOU: undefined,
    DATA_CANCELAMENTO: undefined,
    DATA_EMISSAO: '',
    MODELO_NOTA: undefined,
    SERIE_NOTA: undefined,
    CFOP_NOTA: undefined,
    BASECALCULOICMS: undefined,
    VALORICMS: undefined,
    BASECALCULOICMSST: undefined,
    VALORICMSST: undefined,
    VALORFECP: undefined,
    VALORFECPST: undefined,
    VALORFECPSTRet: undefined,
    VALORTOTALPRODUTOS: undefined,
    VALORFRETE: undefined,
    VALORSEGURO: undefined,
    VALORDESCONTO: undefined,
    VALORDESPESASACESSORIAS: undefined,
    VALORIPI: undefined,
    VALORII: undefined,
    VALORTOTALNOTA: undefined,
    ID_PAFECF: undefined,
    HORA: undefined,
    ECF: undefined,
    DAV: undefined,
    CCF: undefined,
    COO: undefined,
    PDV: undefined,
    TABELA: undefined,
    NOME_ADQUIRENTE: undefined,
    CNPJ_CPF: undefined,
    DANFE: undefined,
    TIPO_NF: undefined,
    ARQ_XML: undefined,
    DATA_ENTRADA: undefined,
    GNRE: undefined,
    FECP: undefined,
    CFOP_ESCRITURACAO: undefined,
    ENDERECO: undefined,
    ENDERECO_NUM: undefined,
    ENDERECO_CPL: undefined,
    BAIRRO: undefined,
    CIDADE: undefined,
    UF: undefined,
    CEP: undefined,
    IBGE_MUN: undefined,
    IBGE_CID: undefined,
    EXPEDICAO: undefined,
    TRANSPORTADORA: undefined,
    ID_MVE: undefined,
    ROTEIRO: undefined,
    STATUS: undefined,
    LOCAL_CONFERENCIA: undefined,
    VAI_CARREGAR: undefined,
    TRANS_QTD: undefined,
    PV_AGUARDAR: undefined,
    ID_OBS_NOTA: undefined,
    ENTREGA_SAIDA: undefined,
    ENTREGA_CHEGADA: undefined,
    REF_EMISSAO: undefined,
    REF_DOC: undefined,
    REF_DANFE: undefined,
    TIPO_CARREGA: undefined,
    DATA_COLETA: undefined,
    ID_PEDIDO: undefined,
    ANOTACAO: undefined,
    PROTOCOLO_NFE: undefined,
    IE: undefined,
    ID_NFCE: undefined,
    ID_CONDICAO_PGTO: undefined,
    ID_MECANICO: undefined,
    FRETE_POR_CONTA: undefined,
    MAIS_DIAS: undefined,
    LOCAL: undefined,
    ID_ARMAZEM: undefined,
    OBS_NF: undefined,
    PROGRAMA_FIDELIDADE: undefined,
    CNF: undefined,
    ID_PEDIDO_ECOMMERCE: undefined,
    LIDO: undefined,
    ID_TIPO_VENDA: undefined,
    Id_WMS: undefined,
    INTERMEDIADOR: undefined,
    INTERMEDIADOR_CNPJ: undefined,
    INTERMEDIADOR_ID: undefined,
    STATUS_INTEGRADOR: undefined,
    CLIENTE: {
      CLIENTE: 0,
      NOME: '',
      ENDERECO: '',
      BAIRRO: '',
      CIDADE: '',
      UF: '',
      CEP: '',
      CIC: '',
      DT_CADASTRO: '',
      DT_NASCIMENTO: '',
      DT_ULT_COMPRA: '',
      INSC_IDENT: '',
      TELEFONE: '',
      FAX: '',
      EMAIL: '',
      BLOQUEADO: '',
      MOTIVO: '',
      P1_DE: 0,
      P1_ATE: 0,
      P1_VENCIMENTO: 0,
      P2_DE: 0,
      P2_ATE: 0,
      P2_VENCIMENTO: 0,
      USARLIMITE: '',
      LIMITE: 0,
      DESCONTO: '',
      OBS: '',
      VALOR_DESCONTO: 0,
      ECF: '',
      BOLETO: '',
      CARTEIRA: '',
      ROTA: 0,
      TAXA_ENTREGA: 0,
      CLASSIFICACAO: 0,
      FRETE_POR_CONTA: '',
      FRETE_TIPO: '',
      ACRESCIMO_NOTA: 0,
      VENDEDOR: 0,
      OS: '',
      TIPO_FAT: '',
      MESSAGEM_FINANCEIRO: '',
      ENDERECO_NUM: '',
      ENDERECO_CPL: '',
      ENDERECO_COD_MUN: 0,
      ENDERECO_COD_UF: 0,
      Tabela: '',
      ATUALIZAR: '',
      CONDICAO_PAGAMENTO: '',
      APELIDO: '',
      EMAIL_FINANCEIRO: '',
      DESCONTO_AVISTA: 0,
      TRANSPORTADORA: 0,
      ID_CONDICAO: 0,
      FROTA: '',
      IDENTIDADE: '',
      MENSAGEM_FINANCEIRO: '',
      GRUPO: 0,
      END_ENTREGA: '',
      INSCRICAO_M: '',
      LIMITE_CHEQUE: 0,
      META: 0,
      SOMENTE_NFE: '',
      VENDEDOR_INTERNO: 0,
      DATA_ATUALIZACAO: '',
      GEO_LAT: '',
      GEO_LNG: '',
      DDA: '',
      V100: '',
      TIPO_CLIENTE: '',
      AtualizarRegiao: '',
      SENHA: '',
      EMAIL_VENDA_DIRETA: '',
      SENHA_VENDA_DIRETA: '',
      PERC_VENDA_DIRETA: 0,
      ConsumidorFinal: '',
      DESCONTO_BOLETO: '',
      REGIAO: {
        ID: 0,
        DESCRICAO: '',
        CARENCIA: 0,
        COMISSAO: 0,
        Locais_List: [],
      },
      OFICINA: '',
      Telefones: [],
      FollowUpList: [],
      AgendamentosList: [],
      PendenciasList: [],
    },
    FORNECEDOR: '',
    VENDEDOR: {
      VENDEDOR: 0,
      NOME: '',
      ENDERECO: '',
      BAIRRO: '',
      CIDADE: '',
      UF: '',
      CEP: '',
      TELEFONE: '',
      SENHA: '',
      ATUALIZAR: '',
      COMISSAO: 0,
      CTPS: '',
      FUNCAO: '',
      ADMISSAO: '',
      DEMISSAO: '',
      SALARIO: 0,
      VALE_TRANSPORTE: 0,
      NASCIMENTO: '',
      CPF: '',
      IDENTIDADE: '',
      ESTADO_CIVIL: '',
      PIS: '',
      NACIONALIDADE: '',
      NATURALIDADE: '',
      CONJUGE: '',
      EMAIL: '',
      CELULAR: '',
      ATIVO: '',
      VENDA: '',
      TIPO_VENDEDOR: '',
      CARTAO_NUMERO: '',
      CARTAO_MATRICULA: '',
      META_MARKUP: 0,
      META_INDEXADOR: 0,
      SETOR: '',
      TABELAS_PERMITIDAS: '',
    },
    REGISTRO_NF: undefined,
    ID_INTEGRADOR: undefined,
    Itens_List: [],
    Recebimento_List: '',
    Eventos_List: '',
  },
  List: {
    Qtd_Registros: 0,
    value: [],
  },
  isLoading: false,
  errorMessage: '',
};

export const vendaSlice = createSlice({
  name: 'Venda',
  initialState,
  reducers: {},
  extraReducers(builder) {
    builder
      .addCase(GetVendas.pending, (state) => {
        state.isLoading = true;
        state.errorMessage = '';
      })
      .addCase(
        GetVendas.fulfilled,
        (state, action: PayloadAction<iDataResultTable<iMovimento> | undefined>) => {
          state.isLoading = false;
          if (action.payload) {
            state.List = action.payload;
          }
        },
      )
      .addCase(GetVendas.rejected, (state, action: PayloadAction<any>) => {
        state.isLoading = false;
        state.errorMessage = action.payload;
      });
  },
});

// export const {} = vendaSlice.actions;

export const vendaReducer = vendaSlice.reducer;
